name: Test Packages
on:
  push: 
    branches: 
    - "*"
jobs:
  publish:
    name: Publish
    runs-on: ${{ matrix.os }}
    permissions:
      contents: read
      packages: write
    strategy: 
      fail-fast: false
      matrix: 
        os: [ ubuntu-latest ]
        dotnet: [ '5.0.x' ]
    steps:
    - name: Checkout Code
      uses: actions/checkout@master
    - name: Setup .NET Core - ${{ matrix.dotnet }}@${{ matrix.os }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '${{ matrix.dotnet }}'
    - name: Restore Packages
      env: 
        GITHUB_USERNAME: qkmaxware
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: dotnet restore --configfile nuget.config
    - name: Compile Package
      env:
        # Work around https://github.com/actions/setup-dotnet/issues/29
        DOTNET_ROOT: ${{ runner.tool_cache }}/dncs/${{ matrix.dotnet }}/x64
      run: dotnet build "Astro.Celestia"